### ISSUE TITLE
Handling failures on duties/attester endpoint

### ISSUE THREAD

**Issue by realbigsean** [ethereum/eth2.0-APIs#113]
How should we handle a failure on a single validator in a POST to the attester duties endpoint? The `IndexedErrorMessage` introduced in  #102 won't quite work with this endpoint if it still needs to return successful duties for other validators in the batch.

Suggestion from @paulhauner: make all the non-pubkey fields optional and return null when we don’t know the validator

Another potential option: make the response array fixed-length and ordered based on the request array, and each element of the response array can be nullable

**Comment by mcdee** [comment]
Somewhat depends on the cause of the failure.  If it's down to supplying a garbage validator ID ("fred") then I'd 400 the entire request.  If the issue is that the supplied index doesn't point to an active validator I'd be inclined to provide no output for that validator and move on.  Returned entries have the validator index in them, so if the caller cares about which requested indices do not have a duty they can work it out for themselves.
