### ISSUE TITLE
How could I get proposals/attestations of a validator with count?

### ISSUE THREAD

**Issue by veneris** [ethereum/eth2.0-APIs#124]
Which API...I can't find it...thanks.

**Comment by mpetrunic** [comment]
I don't think we have that api and we cannot really standardize it because client aren't indexing attestations by validator since it's useless to them. Explorers should have api to fetch that, for example: https://beaconcha.in/api/v1/docs/index.html#/Validator/get_api_v1_validator__indexOrPubkey__attestations
https://beaconcha.in/api/v1/docs/index.html#/Validator/get_api_v1_validator__indexOrPubkey__proposals

**Comment by veneris** [comment]
Thanks.
