### ISSUE TITLE
sync_committee_subscriptions - Replace until_epoch with period

### ISSUE THREAD

**Issue by dapplion** [ethereum/eth2.0-APIs#144]
PR https://github.com/ethereum/eth2.0-APIs/pull/136 by @rolfyone has a potential inefficiency if the validator does 1 sync committee period of lookahead and pushes a subscription. With `until_epoch` it will inform the node when to unsubscribe but not when to subscribe.

I believe it would be simpler to replace `until_epoch` with `period`. With a single number the node exactly when that subscription is of interest, and compute `from_epoch` and `until_epoch`

**Comment by ajsutton** [comment]
I don't believe this works.  The validator client should call subscribe a random number of epochs prior to the start of the sync committee period (up to `SYNC_COMMITTEE_SUBNET_COUNT`).  So it is important for the beacon node to subscribe as soon as this call is made and remain subscribed until the end of the period (as indicated by until_epoch).

I'm also not sure there's any value in validator clients using the full look ahead period as sync committee periods are very long and the validator has nothing to do until they're due to subscribe.  For Teku the validator client simply picks the epoch they should subscribe at and waits until then to request duties and send subscription requests.

Using a committee period number here would also be the first place I'm aware of that numbered committee periods are used (certainly in the REST API but its not really even a concept in the beacon spec).

**Comment by mpetrunic** [comment]
@dapplion do you wish to pursue this or can we close?

**Comment by dapplion** [comment]
After implementing @ajsutton PRs I think this is not necessary closing
