### ISSUE TITLE
Version API

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-APIs#28]
Need to figure out a versioning for the API

**Action items**:
* version prefix
* server endpoint to inspect supported versions

## Prefix

At the bare minimum, we should have some "name" (for basic protocol segregation) and a version (e.g. Prysm currently uses `/eth/{version}`).

Questions:
* are there other valuable items (client, os, etc) worth embedding?
    * Seems like server specific values will make APIs more difficult to manage and manually type out..
    * Are there strong arguments in favor of adding some of these vaues?
* `/eth` vs `/eth2` -- any strong preference?
    * we do use `/eth2` in libp2p protocols
    * `/eth2` might be a valuable distinction between consensus protocol and user-land (eth1)
    * `/eth` is nice because the plan is for it all to be one Ethereum protocol sooner rather than later

**refs**
* "something like `Client/v0.0.0/githash/os/other/stuff` [From @tzapu](https://github.com/ethereum/eth2.0-pm/issues/143#issuecomment-616343710)
* `/eth/{version}`] [from @prestonvanloon](https://github.com/ethereum/eth2.0-APIs/issues/25#issuecomment-616243053)
    * "I'd also recommend the `/eth` prefix as to namespace eth from other services if multiple API are being load balanced from the same root URL"

## Version inspection endpoint

Do we expect servers to serve multiple versions simultaneously? Likely.
If so, a single endpoint that returns a list of versions should work.

`/eth/versions` or `/eth/supported_versions` work for everyone? or is there a standard practice we should conform to?

**Comment by rolfyone** [comment]
Generally this is for an evolving api, and a long version number is not ideal. usually specific endpoints are versioned as they change.
so you'd start at v0, or similar short value, and then if make a breaking change, you change the version of that endpoint to v1, and usually continue to support v0 for as long as possible.

Is this the intent here? If so, I think the long version number as shown above will be counter-productive...

in this method, you'd end up with all interfaces at v0, and as a specific endpoint gets altered in an incompatible way, it would be incremented, which means you'll potentially have something like 
```
/v0/beacon/head
/v0/beacon/chainhead
/v1/beacon/chainhead
/v0/beacon/validators
/v1/beacon/validators
/v2/beacon/validators
```
All exported concurrently, and it can potentially become quite messy as a maintainer...

The upside is clients continue to work, and can be encouraged to upgrade the endpoint they're using, where as if we update the version each time across the board, then the entire client breaks until they update.

**Comment by prestonvanloon** [comment]
ETH2 API will almost certainly be evolving as phase 1 and phase 2 are implemented. Some teams have expressed interest in serving ssz requests/responses and changing a data structure, even removing or adding a field, would not be possible. I don't expect clients to support multiple versions of the API in the long term. 

Imagine a timeline like this
- v1beta released with phase 0
- v1beta2 released with phase 1
- v1beta EOL 6 month after v1beta2
- v1 launched with phase 2
- v1beta2 EOL 6 month after v1

With regard to versions, some APIs use semantic versioning, without the dash. I.e. `v1alpha` as an alpha for version 1. https://semver.org/ 

Additionally, an API would promote all of the endpoints to next version instead of upgrading a single endpoint to the next version as I think you are suggesting.

**Comment by rolfyone** [comment]
So as an api maintainer, at a point in time, am i exporting only 1 api, or several versions? Eg when phase 2 is launched, and we're at v1 (from above) then is v1beta still potentially exported by my api? or do i only support v1 and v1beta/* becomes a 404?

**Comment by prestonvanloon** [comment]
@rolfyone Up to client teams to decide that, in my opinion. It sounds turbulent to turn off an API without simultaneously offering the next version, however, it may not be possible to offer both at the same time given the scope of changes in phase 1 or phase 2.

**Comment by mkalinin** [comment]
I think [this](https://restfulapi.net/versioning/) short guide is pretty relevant. Version of the API should be bumped due to the changes that are backward incompatible to the previous version. Usually, it happens when old API gets a major redesign leading to data structure or endpoint shifts. The following should not be considered as a version change:
- new response formats become available
- responses are appended with new data
- new endpoints are added

I, personally, like `/eth/v1/*` namespace. We probably won't be needed for `/eth/v2/*` for pretty long time as our data structures are not going to evolve that fast.

**Comment by tzapu** [comment]
as a clarification, my mention of `Client/v0.0.0/githash/os/other/stuff` was strictly about the return of the `/v1/node/version` endpoint, so it's standardized as well between client implementations
