### ISSUE TITLE
endpoint to get all validator's duties

### ISSUE THREAD

**Issue by tzapu** [ethereum/eth2.0-APIs#50]
sorry if this is already in the proposals, i was not able to identify it.

i think there is a need for an endpoint that returns all validator duties for the next epoch.
basically this `https://pegasyseng.github.io/teku/#operation/postValidatorDuties` without the pubKey filter, or `https://api.prylabs.net/#/BeaconChain/ListValidatorAssignments`

i have seen `/v1/validator/duties/attester/{epoch}` and `/v1/validator/duties/proposer/{epoch}` but one is filtered by pub key and one isn't which feels a bit not homogeneous and they won't give you the full picture anyway, unless both allowed to be called without a pubKey.  

this would be useful for indexers of on chain data, to get responsibilities before they happen and update/alert on them as they happen/are missed.

**Comment by tzapu** [comment]
i guess  this would be a nice to have/helper as you can compose the data from the committees + duties/proposer

**Comment by rolfyone** [comment]
The attester list is quite large potentially, which is probably the logic behind filtering it, but the proposer list should be a great deal smaller, so its probably ok that it doesn't provide the filtering capability.
It might be nice for it to have the filter just so you can do a query and if the response is empty list you can know up front without further coding, and its going to be common to go through that list looking for a specific set of keys, but I don't think you'd want it to be a required input, just optional.
The attester duties might be a problem if its optional pubkeys, because of the volume that's likely to need to be returned...

**Comment by tzapu** [comment]
for my use case, i want to get it all, without any filters :P
the attester list should be similar in size to the committees list, even a bit smaller, so if you can request that and not worry about size i guess you can request this as well

thank you

**Comment by mpetrunic** [comment]
Couple of things:
- proposer and attester duties are separated because in normal validator workflow they aren't being called at the same time. Validator will get proposer duties for current epoch and attester duties for current epoch + 1 (so node can subscribe to appropriate subnet and collect attestations)
- as @rolfyone already said, proposer duties are fixed list of 32 duties and even with pubkey filter, node would have to calculate all 32 anyways, if everyone agrees we can add optional pubkey filter
- attester duties without filter with 50k validators, will result in 50k duties response which is somewhat expensive to calculate and could bring down public node

Have you considered this endpoint: https://ethereum.github.io/eth2.0-APIs/#/Beacon/getEpochCommittees and filtering by slot which will get you all validators indexes that needs to attest at that slot?

**Comment by tzapu** [comment]
thanks @mpetrunic and @rolfyone , the committees endpoint is indeed what i will use. didn't completely realize that when i opened the issue.

out of curiosity, for 50k validators, won t `https://ethereum.github.io/eth2.0-APIs/#/Beacon/getEpochCommittees` have the same problem you mentioned? ie it will return 50k duties + committee indexes on top?

**Comment by mpetrunic** [comment]
> out of curiosity, for 50k validators, won t `https://ethereum.github.io/eth2.0-APIs/#/Beacon/getEpochCommittees` have the same problem you mentioned? ie it will return 50k duties + committee indexes on top?

TBH depends on client implementation, in attester duties endpoint, you are searching committees of each slot in epoch one by one until you find committee which contains some validator from pubkeys query param. 

If you remove that search param you could behave differently and just fetch committee's for each slot but it feels like we shouldn't burden all client teams to have two different implementation depending on whether pubkeys are sent or not. Also in duties endpoint there would be a lot of duplicated data and even data you don't really need (for your use case).

Function used to get assignment for specific validator:
https://github.com/ethereum/eth2.0-specs/blob/v0.12.1/specs/phase0/validator.md#validator-assignments
vs
Function to get assignment for all validators at slot:
https://github.com/ethereum/eth2.0-specs/blob/v0.12.1/specs/phase0/beacon-chain.md#get_beacon_committee
