### ISSUE TITLE
​[Clarification] /eth​/v1​/node​/peers

### ISSUE THREAD

**Issue by AgeManning** [ethereum/eth2.0-APIs#97]
This endpoint has a few interesting fields which would be good to clarify I think. 

I noticed that there wasn't a `count` endpoint. So for apps that just want the count, they have to obtain all the peer data?

For this specific endpoint, there is the `address` field which the examples show a multiaddr. Firstly, what exactly should this address be. Is it simply the multiaddr that can potentially be obtained from the ENR, in which case its likely redundant information, and also an ENR may not contain this information. 
Perhaps this is the "last seen address". I.e the Socket that we observe the connection on?. If so, this potentially could have multiple values for implementations that allow multiple values. Should this then be a comma separated list? 
Also the example shows the TCP port, but most nodes will have UDP also. I guess this is attempting to show just the libp2p listening address, or last seen socket addr on the TCP side?

Another point to clarify is the `state` and `direction` field. In Lighthouse these are grouped into a single enum. If a peer is disconnected, it doesn't have an `ingoing` or `outgoing` state. Can this be nullable in this instance, or do we need to keep track of past connected states for disconnected peers?
In general, if in the future we allow multiple connections per peer, the peer could have both ingoing and outgoing connections. In this case which should be returned?

**Comment by mpetrunic** [comment]
> I noticed that there wasn't a count endpoint. So for apps that just want the count, they have to obtain all the peer data?

We should probably add pagination which should also provide count field but afaik we haven't reached any consensus on how do we wanna implement pagination.

> For this specific endpoint, there is the address field which the examples show a multiaddr. Firstly, what exactly should this address be. Is it simply the multiaddr that can potentially be obtained from the ENR, in which case its likely redundant information, and also an ENR may not contain this information.

I thought this was last peer connection remote address. Do you think it makes sense to put something else? 
Any idea how we should document that better.

> Another point to clarify is the state and direction field. In Lighthouse these are grouped into a single enum. If a peer is disconnected, it doesn't have an ingoing or outgoing state. Can this be nullable in this instance, or do we need to keep track of past connected states for disconnected peers?

I assume you meant inbound/outbound direction (instead of  ingoing or outgoing state). Honestly, I thought every libp2p implementation has history of connection direction. I guess we can maybe make it nullable if it's an issue (or add unknown to enum)?

**Comment by AgeManning** [comment]
Thanks for the quick response: 

> I thought this was last peer connection remote address. Do you think it makes sense to put something else?
Any idea how we should document that better.

Maybe we can add a description or rename to `last_seen_p2p_address`. The p2p indicates its the tcp multiaddr rather than the udp one. 

> I assume you meant inbound/outbound direction (instead of ingoing or outgoing state). Honestly, I thought every libp2p implementation has history of connection direction. I guess we can maybe make it nullable if it's an issue (or add unknown to enum)?

We can sort this out. 

Another question has arisen about the `/node/identity` endpoint. 

There are two fields `p2p_addresses` and `discovery_addresses`. I assume the discovery_addresses are formed from the ENR and so should the p2p_addresses. The example shows `tcp` for an example of the `discovery_addresses` and I assume this is an error, because discovery cannot be contactable on `tcp`. 

So I guess this endpoint just wants us to parse the ENR for them? Is this the desired behaviour here?

**Comment by mpetrunic** [comment]
> There are two fields p2p_addresses and discovery_addresses. I assume the discovery_addresses are formed from the ENR and so should the p2p_addresses. 

They could, you could also form it from cli args for libp2p and discv5 ports and ip addresses. This is node identity, so local addresses may be returned as well.

> The example shows tcp for an example of the discovery_addresses and I assume this is an error, because discovery cannot be contactable on tcp.

It's tcp since I've put only one example for Multiaddrs type. I can try setting multiples or at least override discovery address example.
https://github.com/ethereum/eth2.0-APIs/blob/master/types/p2p.yaml#L66

I can open PR to correct those stuff, so I should change following:
- in `/node/peers` add pagination
- in `/node/peers` change `address` to `last_seen_p2p_address` and add better description
- in `/node/identity` add better example for discovery addresses
- in `/node/identity` add attnets example

Is this ok? is there anything else?

**Comment by AgeManning** [comment]
Perfect. Thanks you :pray: 

I think these guys were one of the few endpoints we hadn't implemented yet. This clarification has helped a lot and we've completed the implementation. 

Thanks again
